### ISSUE TITLE
Set operation

### ISSUE THREAD

**Issue by StefanoMartin** [project-eutopia/keisan#129]
Hi! Thank you for your amazing library for computations.

I would like to ask if it is possible to include some basic set operation for Array (like in basic Ruby).

In particular:

Difference: [1,2,3] - [2,3,4] = [1]
Intersection: [1,2,3] & [2,3,4] = [2,3]
Union: [1,2,3] | [2,3,4] = [1,2,3,4]

In the meanwhile I will implement them with "define_function" method.

**Comment by project-eutopia** [comment]
Thank you Stefano! Quick question, would it be alright to implement these set operations as functions rather than operators? For example `a.difference(b)` instead of `a - b`? This should give you the same functionality, and would be very easy to add. Otherwise I will need to modify the behavior of `-`, `&`, and `|` when working on lists.

**Comment by StefanoMartin** [comment]
For me it is fine. But keep in mind that it is a personal preference. 

The behaviour that I described above is the default one of Ruby Array, so if you are not following that convention then it is better you make clear in the documentation.

**Comment by project-eutopia** [comment]
@StefanoMartin Alright that sounds good. I opened PR #130, and added these functions to the sample code in the README. Let me know if that will address this issue, and if so I will merge it and push a new gem version.

**Comment by StefanoMartin** [comment]
It sound good for me! Thank you a lot! Very fast to implement it.

**Comment by project-eutopia** [comment]
And thanks for your contribution! Gem version 0.9.1 should be live with these new functions now.
