### ISSUE TITLE
Remove `activesupport` dependency

### ISSUE THREAD

**Issue by project-eutopia** [project-eutopia/keisan#66]
Required changes:

- Implement `Array.split`
- Implement `Array.wrap`
- Implement `Object.present?` and `Object.blank?`
- Implement `String.underscore`
- Change `try` to safe navigation operator `&.`

**Comment by shioyama** [comment]
Rather than monkey-matching core classes, I'd recommend creating a separate class which has all the methods and calling them explicitly, like [this](https://github.com/shioyama/mobility/blob/f84894423da12ad777eb23d5d0fe35a308d75745/lib/mobility/util.rbhttps://github.com/shioyama/mobility/blob/f84894423da12ad777eb23d5d0fe35a308d75745/lib/mobility/util.rb).

**Comment by project-eutopia** [comment]
@shioyama Thanks for the helpful comment.  I agree with your suggestion :+1:

I knew some of the above methods were ActiveSupport features, but some I was surprised about.  In particular I wish `Array.split` was a native Ruby method, as it fits nicely along with `String.split`.

**Comment by shioyama** [comment]
I learned that you can get the same result as `Array.wrap(...)`  by just calling `Array(...)`. `Array` is actually a *method* on [Kernel](https://ruby-doc.org/core-2.5.0/Kernel.html#method-i-Array). Neat eh?

**Comment by project-eutopia** [comment]
That is neat, and it would work here.  Reading up it seems that the notation `[*to_be_wrapped]` is equivalent to `Array(to_be_wrapped)`, but I would prefer using `Array`.

**Comment by project-eutopia** [comment]
@shioyama Thanks for your helpful advice.  I removed the dependency in #78
